### PR TITLE
feat: Update UI and add drag & drop, and pasting from clipboard to every tool

### PR DESCRIPTION
**Pull request by vys69**
Reference: [#23](https://github.com/t3dotgg/quickpic/issues/23)

## CHANGES:
- Added drag & drop (no library)
- Added a cooler scale selector (also no lib)
- Added a faux-drop zone so users know they can drag and drop
- Linted and ran prettier write on ALL files.
- Added pasting from clipboard
- Added custom SVG scale
  - Max: 64px 
- Added custom border rounding
  - Max: 999px 
- Added shift & alt modifiers to custom inputs
  - Shift +10, alt + 0.1

## OVERVIEW ⏬:

https://github.com/user-attachments/assets/b4524e9c-9007-49ae-b1c1-3381ab9eb8ba

## Proof of Lint && Prettier
image

### Tool landing pages:

Square tool:
image

Round tool
image

SVG tool
image

### After image upload:

Square tool:
image

Round tool
image

SVG tool
image

### Pasting from clipboard in action:
https://github.com/user-attachments/assets/3416be2b-937c-40ff-8aee-f4252bb19e1b

### CODE REVIEW

**Comment by vys69** [comment]
Sorry about such a lizzo-sized pull request, I forgot to make a new branch and PR for my clipboard changes 😅

**Comment by t3dotgg** [comment]
Dragging a new SVG does not appear to clear the old one :(

**Comment by vys69** [comment]
> Dragging a new SVG does not appear to clear the old one :(

One sec 🤭

**Comment by vys69** [comment]
> > Dragging a new SVG does not appear to clear the old one :(
> 
> One sec 🤭

image
why isnt it working

**Comment by vys69** [comment]
> It's because the input no longer exists. It sucks, but this should be re-implemented to share the state of "what file is being stored right now"
> 
> image

I haven't slept since my first push 😭I need some **_sleep_**

Be back tomorrow 💯

**Comment by vys69** [comment]
nvm. im goated. @t3dotgg 

https://github.com/user-attachments/assets/4cc794f4-58e9-40ac-b90c-d56bab449ead

**Comment by vys69** [comment]
Create utils to allow dragging in new files: [#e131867](https://github.com/t3dotgg/quickpic/pull/40/commits/e131867a33123e937c2eb60d3b10c074810bd9a3)

Making it work. I don't feel like explaining: [#9579fb3](https://github.com/t3dotgg/quickpic/pull/40/commits/9579fb3d3facb1a02855cb27bae27aa5bbe01ff5)

Create no-op function, frick u linter: [#b9fd87f](https://github.com/t3dotgg/quickpic/pull/40/commits/b9fd87f7762d6a205442bf4f299dec49c950154a)

**Comment by t3dotgg** [comment]
My preferred strat would be to hoist the "uploaded file" management entirely, and just pass down a doUpload function + the file state. I'm happy to take that on myself on top of your work here, or you can do it. Whatever you prefer :)

**Pull request closed without merging**
