### PR TITLE
Added docker image and compose

### LINKED ISSUE #90: Please add docker image
Love this project but can you make it into a docker image so it will be much easier to run?

Thank you!

### PR DESCRIPTION
**Pull request by Bashamega**
Please make sure you do the following before filing your PR:
- [x] Provide a video or screenshots of any visual changes made
- [x] Run `pnpm run check` and make sure everything passes

Hello:)
I have added a docker image and a docker compose, for people who prefer to use docker.

Preview

https://github.com/user-attachments/assets/2e1fdf4e-802d-4298-b3b0-ad0279c61061

closes #90

### CODE REVIEW

**Comment by Husky-Devel** [comment]
Nice, Very useful addition

**Comment by t3dotgg** [comment]
No.

**Comment by Bashamega** [comment]
> No.

Can i ask why?

**Comment by zacgoodwin** [comment]
Being able to deploy with compose would help me out quite a bit with this.

**Comment by zacgoodwin** [comment]
@Bashamega - Do you think we could fork this or maybe just take some of the learnings and head over to https://github.com/danvergara/morphos ?

**Comment by Bashamega** [comment]
> @Bashamega - Do you think we could fork this or maybe just take some of the learnings and head over to https://github.com/danvergara/morphos ?

Hello:)
This repositor is for go not next js. Also I don't think @t3dotgg want to add docker to this project.

**Comment by ametysti** [comment]
> No.

very professional from you xD wtf

**Comment by Bashamega** [comment]
Dear Mr. @t3dotgg ,

I’m reaching out to address the abrupt closure of PR #92.

This PR was submitted with the intent to benefit the open-source community, particularly those who prefer Docker and may wish to self-host the project. Closing it with a simple "no" lacks transparency and dismisses the efforts put into contributing to this repository.

Could you please clarify the reasoning behind this decision? I believe a more constructive discussion would be in the best interest of the project and its contributors.

Looking forward to hearing your thoughts.

Best regards,

**Comment by ametysti** [comment]
Being selfish equals being an asshole which is very sad, but it can be seen whole project's author's personality not forgetting DarkViperAU's video. You're better off forking this project and add Docker there if you like that, nothing stops you from that!

Edit just to address that it is Theo's decision if to add docker or not, but the simple answer "No.", even with the ending dot, proves enough what i said in the beginning.

Hope this helps @Bashamega, and i do not recommend interacting with this dude in any way

**Comment by zacgoodwin** [comment]
Interesting; thanks for pointing that out.

**Comment by Bashamega** [comment]
Thank you very much @ametysti. I won't contribute to this repo any ways

**Pull request closed without merging**
