### PR TITLE
feat: Add drag and drop

### PR DESCRIPTION
**Pull request by Iamsidar07**
[Screencast from 2024-11-10 09-10-42.webm](https://github.com/user-attachments/assets/33869330-6c7c-42dc-bcf8-f9bb0526ea4b)

### CODE REVIEW

**Comment by Jontes-Tech** [comment]
Hover state with dragged file is styled for lightmode.

**Comment by Iamsidar07** [comment]
I added the styles for dark mode also

**Comment by t3dotgg** [comment]
https://github.com/t3dotgg/quickpic/issues/23

**Comment by vys69** [comment]
Damn 😭 I JUST finished my version of it

**Comment by vys69** [comment]
> Damn 😭 I JUST finished my version of it

Yours 100% looks better, but this is mine:
Arc_eKkdsp8zQj

**Pull request closed without merging**
